@baseUrl = http://localhost:8080
@apiKey = {{createAccount.response.body.api_key}}

### Creating new accounts
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@doe.com"
}

### Recovering accounts (GET)
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}


### Create a new invoice
# @name createInvoice
POST {{baseUrl}}/invoice
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "amount": 100.50,
    "description": "Teste de fatura",
    "payment_type": "credit_card",
    "card_number": "4111111111111111",
    "cvv": "123",
    "expiry_month": 12,
    "expiry_year": 2025,
    "cardholder_name": "John Doe"
}

### Get an specif invoice
@invoiceId = {{createInvoice.response.body.id}}
GET {{baseUrl}}/invoice/{{invoiceId}}
X-API-Key: {{apiKey}}

### Try creating a high value invoice (> 10000)
POST {{baseUrl}}/invoice
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "amount": 15000,
    "description": "Teste de fatura com valor alto",
    "payment_type": "credit_card",
    "card_number": "4111111111111111",
    "cvv": "123",
    "expiry_month": 12,
    "expiry_year": 2025,
    "cardholder_name": "John Doe"
} 
